#! /bin/sh

bspc config border_width        2
bspc config window_gap          5

bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config click_to_focus	true

bspc monitor -d 0000 0001 0010 0011 0100 0101 0110 0111 

bspc rule -a Gimp desktop=^8 follow=on floating=on
bspc rule -a Chromium desktop=^2
bspc rule -a mplayer2 floating=on
bspc rule -a Screenkey manage=off
